

### local env
### 
Get http://localhost:5000/api/platform

###
POST http://localhost:5000/api/platform
content-type: application/json

{
    "Name":"Docker",
    "Publisher":"Docker",
    "Cost":"Free"
}

### docker env
###
Get http://localhost:8080/api/platform


### K8S env
GET http://localhost:32219/api/platform